version: "3"

tasks:
  disable-awdl:
    desc: Disbales AWDL
    cmds:
      - "bash <(curl -sL https://www.meter.com/awdl.sh)"

  disable-awdl-service:
    desc: Disables AWDL as a service
    cmds:
      - "bash <(curl -sL https://www.meter.com/awdl.sh)"

  reenable-awdl:
    desc: Re-enables AWDL
    cmds:
      - "curl -s https://raw.githubusercontent.com/meterup/awdl_wifi_scripts/main/cleanup-and-reenable-awdl.sh | bash &> /dev/null"

  rollup_project:
    desc: Collects the contents of specified file types in current directory and writes them to a single well-formatted markdown file
    dir: "{{USER_WORKING_DIR}}"
    vars:
      FILE_TYPES: '{{.FILE_TYPES | default "go"}}'
      OUTPUT_FILE: '{{.OUTPUT_FILE | default ""}}'
    cmds:
      - |
        IFS=',' read -ra types <<< "$FILE_TYPES"
        if [ -z "$OUTPUT_FILE" ]; then
          parent_dir=$(basename "$(dirname "$PWD")")
          timestamp=$(date +%Y%m%d_%H%M%S)
          OUTPUT_FILE="${parent_dir}_rollup_${timestamp}.md"
        fi
        for type in "${types[@]}"; do
          find . -name "*.$type" -not -path '*/\.*' | sort | while read -r file; do
            echo "## $file"
            echo
            echo '```'"$type"
            cat "$file"
            echo '```'
            echo
          done
        done > "$OUTPUT_FILE"
