import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 13
offset.y = 1

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 5, y = 5 }
option_as_alt = "OnlyLeft"

[scrolling]
history = 25000

[cursor]
style.shape = "Beam"
thickness = 0.3
