import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 12

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 5, y = 5 }
option_as_alt = "Both"
dynamic_padding = true
decorations = "Buttonless"

[scrolling]
history = 25000

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001B[H"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001B[F"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"
