theme = "rose_pine_moon"

[editor.cursor-shape]
normal = "underline"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[editor.auto-save]
after-delay.enable = true

[keys.insert]
C-S = ":write"

[keys.normal]
C-S = ":write"

[keys.select]
C-S = ":write"
