[[language]]
name = "markdown"
scope = "source.md"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "go"
scope = "source.go"
auto-format = true

[[language]]
name = "terraform"
scope = "scope.terraform"
file-types = ["tfvars", "tf"]
auto-format = false

[[language]]
name = "json"
auto-format = false
