[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "terraform"
file-types = ["tfvars"]
auto-format = false
